services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.development
    expose:
      - 5432
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
  
  nats:
    image: docker.io/nats:2.9.20-alpine
    expose:
      - 4222
    ports:
      - "4222:4222"
      - "8222:8222"

  backend:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - nats
