services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env.development
    expose:
      - 5432
    ports:
      - 5432:5432

  redis:
    container_name: japahubs_redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - 6379:6379
  
  nats:
    image: docker.io/nats:2.9.20
    expose:
      - 4222
    ports:
      - 4222:4222
      - 8222:8222
    command:
      - "--js"
